"""Auto-generated quest assets — The Trial of St James's Hall

Generated by the Cardinal System Social Control module.
Source: https://en.wikipedia.org/wiki/St_James's_Hall
Do not edit by hand; regenerate through quest_generator.py.
"""
from __future__ import annotations

import random

QUEST_TITLE = "The Trial of St James's Hall"
MAP_ARCHETYPE = 'horizontal'
NARRATIVE = "Whispers of St James's Hall have reached the floating castle. An anomaly reshapes the land into a horizontal trial. Only those who unravel its origin may claim the reward."

STAGES = [
    {
        "stage": 1,
        "description": "Investigate the rumors surrounding St James's Hall. St. James's Hall was a concert hall in London that opened on 25 March 1858, designed by architect and artist Owen Jones, who had decorated the interior of the Crystal Palace. It was situated between t",
        "objective": "Speak with the Chronicler and find the anomaly site."
    },
    {
        "stage": 2,
        "description": "The anomaly's guardians emerge to test challengers.",
        "objective": "Defeat 3 Anomaly Guardians."
    },
    {
        "stage": 3,
        "description": "The heart of the horizontal reveals itself.",
        "objective": "Defeat the Avatar of St James's Hall and seal the anomaly."
    }
]

NPC_DIALOGUE = {
    "The Chronicler": "Traveler... the tale of St James's Hall is older than this castle. Listen well.",
    "Lost Scout": "I saw the guardians with my own eyes. Turn back, or arm yourself."
}

ENEMIES = [
    {
        "name": "Anomaly Guardian",
        "damage": 15,
        "hp": 121,
        "reward_gold": 52,
        "genome": {
            "timing_jitter": -0.2163,
            "damage_jitter": 0.1842,
            "combo_seed": 2090852888,
            "combo_shuffle_depth": 1,
            "resistance_vector": {
                "physical": 0.2935,
                "magic": 0.3492,
                "ranged": 0.0226
            },
            "entropy_at_birth": 0.9465
        }
    },
    {
        "name": "Avatar of St James's Hall",
        "damage": 35,
        "hp": 440,
        "reward_gold": 236,
        "genome": {
            "timing_jitter": 0.0844,
            "damage_jitter": -0.2159,
            "combo_seed": 376361390,
            "combo_shuffle_depth": 3,
            "resistance_vector": {
                "physical": 0.1233,
                "magic": 0.2316,
                "ranged": 0.1429
            },
            "entropy_at_birth": 0.9465
        }
    }
]

REWARDS = [
    {
        "item": "Relic of St James's Hall",
        "quantity": 1
    },
    {
        "item": "Health Potion",
        "quantity": 3
    }
]


class Quest:
    """Stage machine for "The Trial of St James's Hall"."""

    def __init__(self) -> None:
        self.stage = 0
        self.completed = False

    def check_trigger(self, player_level: int = 1, floor: int = 1) -> bool:
        """The quest becomes available once any player reaches floor 2."""
        return not self.completed and self.stage == 0 and floor >= 2

    def advance_stage(self) -> dict | None:
        if self.completed:
            return None
        if self.stage < len(STAGES):
            self.stage += 1
            return STAGES[self.stage - 1]
        self.complete()
        return None

    def complete(self) -> list[dict]:
        self.completed = True
        return REWARDS

    def current_objective(self) -> str:
        if self.completed:
            return "Quest complete."
        if 0 < self.stage <= len(STAGES):
            return STAGES[self.stage - 1]["objective"]
        return "Speak to " + (list(NPC_DIALOGUE) or ["the Chronicler"])[0]


def spawn_enemy(rng: random.Random | None = None) -> dict:
    """Spawn one quest enemy using its GDD stats + persisted genome."""
    rng = rng or random.Random()
    enemy = dict(rng.choice(ENEMIES))
    enemy.setdefault("genome", {})
    return enemy


def npc_line(name: str) -> str:
    return NPC_DIALOGUE.get(name, "...")
