"""Auto-generated quest assets — The Trial of Ragnarök

Generated by the Cardinal System Social Control module.
Source: https://en.wikipedia.org/wiki/Ragnar%C3%B6k
Do not edit by hand; regenerate through quest_generator.py.
"""
from __future__ import annotations

import random

QUEST_TITLE = 'The Trial of Ragnarök'
MAP_ARCHETYPE = 'horizontal'
NARRATIVE = 'Whispers of Ragnarök have reached the floating castle. An anomaly reshapes the land into a horizontal trial. Only those who unravel its origin may claim the reward.'

STAGES = [
    {
        "stage": 1,
        "description": "Investigate the rumors surrounding Ragnar\u00f6k. In Norse mythology, Ragnar\u00f6k is a foretold series of impending events, including a great battle in which numerous great Norse mythological figures will perish ; it will entail a catastrophic series of",
        "objective": "Speak with the Chronicler and find the anomaly site."
    },
    {
        "stage": 2,
        "description": "The anomaly's guardians emerge to test challengers.",
        "objective": "Defeat 3 Anomaly Guardians."
    },
    {
        "stage": 3,
        "description": "The heart of the horizontal reveals itself.",
        "objective": "Defeat the Avatar of Ragnar\u00f6k and seal the anomaly."
    }
]

NPC_DIALOGUE = {
    "The Chronicler": "Traveler... the tale of Ragnar\u00f6k is older than this castle. Listen well.",
    "Lost Scout": "I saw the guardians with my own eyes. Turn back, or arm yourself."
}

ENEMIES = [
    {
        "name": "Anomaly Guardian",
        "damage": 19,
        "hp": 133,
        "reward_gold": 53,
        "genome": {
            "timing_jitter": -0.0454,
            "damage_jitter": -0.1198,
            "combo_seed": 717672244,
            "combo_shuffle_depth": 2,
            "resistance_vector": {
                "physical": 0.228,
                "magic": 0.2216,
                "ranged": 0.0015
            },
            "entropy_at_birth": 0.65
        }
    },
    {
        "name": "Avatar of Ragnar\u00f6k",
        "damage": 31,
        "hp": 414,
        "reward_gold": 215,
        "genome": {
            "timing_jitter": 0.2282,
            "damage_jitter": 0.2154,
            "combo_seed": 2109714870,
            "combo_shuffle_depth": 1,
            "resistance_vector": {
                "physical": 0.0338,
                "magic": 0.0002,
                "ranged": 0.0096
            },
            "entropy_at_birth": 0.65
        }
    }
]

REWARDS = [
    {
        "item": "Relic of Ragnar\u00f6k",
        "quantity": 1
    },
    {
        "item": "Health Potion",
        "quantity": 3
    }
]


class Quest:
    """Stage machine for 'The Trial of Ragnarök'."""

    def __init__(self) -> None:
        self.stage = 0
        self.completed = False

    def check_trigger(self, player_level: int = 1, floor: int = 1) -> bool:
        """The quest becomes available once any player reaches floor 2."""
        return not self.completed and self.stage == 0 and floor >= 2

    def advance_stage(self) -> dict | None:
        if self.completed:
            return None
        if self.stage < len(STAGES):
            self.stage += 1
            return STAGES[self.stage - 1]
        self.complete()
        return None

    def complete(self) -> list[dict]:
        self.completed = True
        return REWARDS

    def current_objective(self) -> str:
        if self.completed:
            return "Quest complete."
        if 0 < self.stage <= len(STAGES):
            return STAGES[self.stage - 1]["objective"]
        return "Speak to " + (list(NPC_DIALOGUE) or ["the Chronicler"])[0]


def spawn_enemy(rng: random.Random | None = None) -> dict:
    """Spawn one quest enemy using its GDD stats + persisted genome."""
    rng = rng or random.Random()
    enemy = dict(rng.choice(ENEMIES))
    enemy.setdefault("genome", {})
    return enemy


def npc_line(name: str) -> str:
    return NPC_DIALOGUE.get(name, "...")
