"""Auto-generated quest assets — The Trial of Vikings

Generated by the Cardinal System Social Control module.
Source: https://en.wikipedia.org/wiki/Vikings
Do not edit by hand; regenerate through quest_generator.py.
"""
from __future__ import annotations

import random

QUEST_TITLE = 'The Trial of Vikings'
MAP_ARCHETYPE = 'horizontal'
NARRATIVE = 'Whispers of Vikings have reached the floating castle. An anomaly reshapes the land into a horizontal trial. Only those who unravel its origin may claim the reward.'

STAGES = [
    {
        "stage": 1,
        "description": "Investigate the rumors surrounding Vikings. Vikings were a seafaring people originally from Scandinavia, who from the late 8th to the late 11th centuries raided, pirated, traded, and settled throughout parts of Europe. They voyaged as far as th",
        "objective": "Speak with the Chronicler and find the anomaly site."
    },
    {
        "stage": 2,
        "description": "The anomaly's guardians emerge to test challengers.",
        "objective": "Defeat 3 Anomaly Guardians."
    },
    {
        "stage": 3,
        "description": "The heart of the horizontal reveals itself.",
        "objective": "Defeat the Avatar of Vikings and seal the anomaly."
    }
]

NPC_DIALOGUE = {
    "The Chronicler": "Traveler... the tale of Vikings is older than this castle. Listen well.",
    "Lost Scout": "I saw the guardians with my own eyes. Turn back, or arm yourself."
}

ENEMIES = [
    {
        "name": "Anomaly Guardian",
        "damage": 19,
        "hp": 109,
        "reward_gold": 65,
        "genome": {
            "timing_jitter": -0.0265,
            "damage_jitter": 0.1127,
            "combo_seed": 350047376,
            "combo_shuffle_depth": 1,
            "resistance_vector": {
                "physical": 0.29,
                "magic": 0.235,
                "ranged": 0.2953
            },
            "entropy_at_birth": 0.7172
        }
    },
    {
        "name": "Avatar of Vikings",
        "damage": 36,
        "hp": 431,
        "reward_gold": 280,
        "genome": {
            "timing_jitter": -0.0948,
            "damage_jitter": -0.1666,
            "combo_seed": 994252427,
            "combo_shuffle_depth": 2,
            "resistance_vector": {
                "physical": 0.1177,
                "magic": 0.2284,
                "ranged": 0.2949
            },
            "entropy_at_birth": 0.7172
        }
    }
]

REWARDS = [
    {
        "item": "Relic of Vikings",
        "quantity": 1
    },
    {
        "item": "Health Potion",
        "quantity": 3
    }
]


class Quest:
    """Stage machine for 'The Trial of Vikings'."""

    def __init__(self) -> None:
        self.stage = 0
        self.completed = False

    def check_trigger(self, player_level: int = 1, floor: int = 1) -> bool:
        """The quest becomes available once any player reaches floor 2."""
        return not self.completed and self.stage == 0 and floor >= 2

    def advance_stage(self) -> dict | None:
        if self.completed:
            return None
        if self.stage < len(STAGES):
            self.stage += 1
            return STAGES[self.stage - 1]
        self.complete()
        return None

    def complete(self) -> list[dict]:
        self.completed = True
        return REWARDS

    def current_objective(self) -> str:
        if self.completed:
            return "Quest complete."
        if 0 < self.stage <= len(STAGES):
            return STAGES[self.stage - 1]["objective"]
        return "Speak to " + (list(NPC_DIALOGUE) or ["the Chronicler"])[0]


def spawn_enemy(rng: random.Random | None = None) -> dict:
    """Spawn one quest enemy using its GDD stats + persisted genome."""
    rng = rng or random.Random()
    enemy = dict(rng.choice(ENEMIES))
    enemy.setdefault("genome", {})
    return enemy


def npc_line(name: str) -> str:
    return NPC_DIALOGUE.get(name, "...")
