"""Auto-generated quest assets — The Trial of Murder of Austin Metcalf

Generated by the Cardinal System Social Control module.
Source: https://en.wikipedia.org/wiki/Murder_of_Austin_Metcalf
Do not edit by hand; regenerate through quest_generator.py.
"""
from __future__ import annotations

import random

QUEST_TITLE = 'The Trial of Murder of Austin Metcalf'
MAP_ARCHETYPE = 'horizontal'
NARRATIVE = 'Whispers of Murder of Austin Metcalf have reached the floating castle. An anomaly reshapes the land into a horizontal trial. Only those who unravel its origin may claim the reward.'

STAGES = [
    {
        "stage": 1,
        "description": "Investigate the rumors surrounding Murder of Austin Metcalf. On April 2, 2025, Austin Metcalf, a White 17-year-old student at Memorial High School, was murdered by Karmelo Anthony, a Black Centennial High School student of the same age, while attending a school",
        "objective": "Speak with the Chronicler and find the anomaly site."
    },
    {
        "stage": 2,
        "description": "The anomaly's guardians emerge to test challengers.",
        "objective": "Defeat 3 Anomaly Guardians."
    },
    {
        "stage": 3,
        "description": "The heart of the horizontal reveals itself.",
        "objective": "Defeat the Avatar of Murder of Austin Metcalf and seal the anomaly."
    }
]

NPC_DIALOGUE = {
    "The Chronicler": "Traveler... the tale of Murder of Austin Metcalf is older than this castle. Listen well.",
    "Lost Scout": "I saw the guardians with my own eyes. Turn back, or arm yourself."
}

ENEMIES = [
    {
        "name": "Anomaly Guardian",
        "damage": 21,
        "hp": 104,
        "reward_gold": 55,
        "genome": {
            "timing_jitter": -0.3213,
            "damage_jitter": 0.0445,
            "combo_seed": 1053301296,
            "combo_shuffle_depth": 1,
            "resistance_vector": {
                "physical": 0.226,
                "magic": 0.2164,
                "ranged": 0.1915
            },
            "entropy_at_birth": 1.0
        }
    },
    {
        "name": "Avatar of Murder of Austin Metcalf",
        "damage": 34,
        "hp": 395,
        "reward_gold": 219,
        "genome": {
            "timing_jitter": -0.3678,
            "damage_jitter": -0.0474,
            "combo_seed": 1166682252,
            "combo_shuffle_depth": 1,
            "resistance_vector": {
                "physical": 0.3119,
                "magic": 0.0327,
                "ranged": 0.1617
            },
            "entropy_at_birth": 1.0
        }
    }
]

REWARDS = [
    {
        "item": "Relic of Murder of Austin Metcalf",
        "quantity": 1
    },
    {
        "item": "Health Potion",
        "quantity": 3
    }
]


class Quest:
    """Stage machine for 'The Trial of Murder of Austin Metcalf'."""

    def __init__(self) -> None:
        self.stage = 0
        self.completed = False

    def check_trigger(self, player_level: int = 1, floor: int = 1) -> bool:
        """The quest becomes available once any player reaches floor 2."""
        return not self.completed and self.stage == 0 and floor >= 2

    def advance_stage(self) -> dict | None:
        if self.completed:
            return None
        if self.stage < len(STAGES):
            self.stage += 1
            return STAGES[self.stage - 1]
        self.complete()
        return None

    def complete(self) -> list[dict]:
        self.completed = True
        return REWARDS

    def current_objective(self) -> str:
        if self.completed:
            return "Quest complete."
        if 0 < self.stage <= len(STAGES):
            return STAGES[self.stage - 1]["objective"]
        return "Speak to " + (list(NPC_DIALOGUE) or ["the Chronicler"])[0]


def spawn_enemy(rng: random.Random | None = None) -> dict:
    """Spawn one quest enemy using its GDD stats + persisted genome."""
    rng = rng or random.Random()
    enemy = dict(rng.choice(ENEMIES))
    enemy.setdefault("genome", {})
    return enemy


def npc_line(name: str) -> str:
    return NPC_DIALOGUE.get(name, "...")
