"""Auto-generated quest assets — The Trial of Disclosure Day

Generated by the Cardinal System Social Control module.
Source: https://en.wikipedia.org/wiki/Disclosure_Day
Do not edit by hand; regenerate through quest_generator.py.
"""
from __future__ import annotations

import random

QUEST_TITLE = 'The Trial of Disclosure Day'
MAP_ARCHETYPE = 'horizontal'
NARRATIVE = 'Whispers of Disclosure Day have reached the floating castle. An anomaly reshapes the land into a horizontal trial. Only those who unravel its origin may claim the reward.'

STAGES = [
    {
        "stage": 1,
        "description": "Investigate the rumors surrounding Disclosure Day. Disclosure Day is a 2026 American science fiction film directed and produced by Steven Spielberg from a screenplay by David Koepp, based on a story by Spielberg. The film features an ensemble cast tha",
        "objective": "Speak with the Chronicler and find the anomaly site."
    },
    {
        "stage": 2,
        "description": "The anomaly's guardians emerge to test challengers.",
        "objective": "Defeat 3 Anomaly Guardians."
    },
    {
        "stage": 3,
        "description": "The heart of the horizontal reveals itself.",
        "objective": "Defeat the Avatar of Disclosure Day and seal the anomaly."
    }
]

NPC_DIALOGUE = {
    "The Chronicler": "Traveler... the tale of Disclosure Day is older than this castle. Listen well.",
    "Lost Scout": "I saw the guardians with my own eyes. Turn back, or arm yourself."
}

ENEMIES = [
    {
        "name": "Anomaly Guardian",
        "damage": 17,
        "hp": 121,
        "reward_gold": 71,
        "genome": {
            "timing_jitter": 0.0565,
            "damage_jitter": 0.0597,
            "combo_seed": 1576475408,
            "combo_shuffle_depth": 3,
            "resistance_vector": {
                "physical": 0.024,
                "magic": 0.0358,
                "ranged": 0.3778
            },
            "entropy_at_birth": 1.0
        }
    },
    {
        "name": "Avatar of Disclosure Day",
        "damage": 28,
        "hp": 383,
        "reward_gold": 281,
        "genome": {
            "timing_jitter": 0.0221,
            "damage_jitter": -0.1274,
            "combo_seed": 1531720164,
            "combo_shuffle_depth": 3,
            "resistance_vector": {
                "physical": 0.115,
                "magic": 0.3397,
                "ranged": 0.322
            },
            "entropy_at_birth": 1.0
        }
    }
]

REWARDS = [
    {
        "item": "Relic of Disclosure Day",
        "quantity": 1
    },
    {
        "item": "Health Potion",
        "quantity": 3
    }
]


class Quest:
    """Stage machine for 'The Trial of Disclosure Day'."""

    def __init__(self) -> None:
        self.stage = 0
        self.completed = False

    def check_trigger(self, player_level: int = 1, floor: int = 1) -> bool:
        """The quest becomes available once any player reaches floor 2."""
        return not self.completed and self.stage == 0 and floor >= 2

    def advance_stage(self) -> dict | None:
        if self.completed:
            return None
        if self.stage < len(STAGES):
            self.stage += 1
            return STAGES[self.stage - 1]
        self.complete()
        return None

    def complete(self) -> list[dict]:
        self.completed = True
        return REWARDS

    def current_objective(self) -> str:
        if self.completed:
            return "Quest complete."
        if 0 < self.stage <= len(STAGES):
            return STAGES[self.stage - 1]["objective"]
        return "Speak to " + (list(NPC_DIALOGUE) or ["the Chronicler"])[0]


def spawn_enemy(rng: random.Random | None = None) -> dict:
    """Spawn one quest enemy using its GDD stats + persisted genome."""
    rng = rng or random.Random()
    enemy = dict(rng.choice(ENEMIES))
    enemy.setdefault("genome", {})
    return enemy


def npc_line(name: str) -> str:
    return NPC_DIALOGUE.get(name, "...")
