"""Auto-generated quest assets — The Trial of The Social Reckoning

Generated by the Cardinal System Social Control module.
Source: https://en.wikipedia.org/wiki/The_Social_Reckoning
Do not edit by hand; regenerate through quest_generator.py.
"""
from __future__ import annotations

import random

QUEST_TITLE = 'The Trial of The Social Reckoning'
MAP_ARCHETYPE = 'dungeon'
NARRATIVE = 'Whispers of The Social Reckoning have reached the floating castle. An anomaly reshapes the land into a dungeon trial. Only those who unravel its origin may claim the reward.'

STAGES = [
    {
        "stage": 1,
        "description": "Investigate the rumors surrounding The Social Reckoning. The Social Reckoning is an upcoming American biographical thriller film written, co-produced, and directed by Aaron Sorkin. It is a spiritual successor to The Social Network (2010), based on the 2021 ",
        "objective": "Speak with the Chronicler and find the anomaly site."
    },
    {
        "stage": 2,
        "description": "The anomaly's guardians emerge to test challengers.",
        "objective": "Defeat 3 Anomaly Guardians."
    },
    {
        "stage": 3,
        "description": "The heart of the dungeon reveals itself.",
        "objective": "Defeat the Avatar of The Social Reckoning and seal the anomaly."
    }
]

NPC_DIALOGUE = {
    "The Chronicler": "Traveler... the tale of The Social Reckoning is older than this castle. Listen well.",
    "Lost Scout": "I saw the guardians with my own eyes. Turn back, or arm yourself."
}

ENEMIES = [
    {
        "name": "Anomaly Guardian",
        "damage": 20,
        "hp": 131,
        "reward_gold": 62,
        "genome": {
            "timing_jitter": -0.3277,
            "damage_jitter": -0.0491,
            "combo_seed": 460766698,
            "combo_shuffle_depth": 2,
            "resistance_vector": {
                "physical": 0.0286,
                "magic": 0.0597,
                "ranged": 0.1664
            },
            "entropy_at_birth": 1.0
        }
    },
    {
        "name": "Avatar of The Social Reckoning",
        "damage": 27,
        "hp": 361,
        "reward_gold": 292,
        "genome": {
            "timing_jitter": 0.0611,
            "damage_jitter": 0.0361,
            "combo_seed": 1309043080,
            "combo_shuffle_depth": 3,
            "resistance_vector": {
                "physical": 0.1654,
                "magic": 0.1132,
                "ranged": 0.014
            },
            "entropy_at_birth": 1.0
        }
    }
]

REWARDS = [
    {
        "item": "Relic of The Social Reckoning",
        "quantity": 1
    },
    {
        "item": "Health Potion",
        "quantity": 3
    }
]


class Quest:
    """Stage machine for 'The Trial of The Social Reckoning'."""

    def __init__(self) -> None:
        self.stage = 0
        self.completed = False

    def check_trigger(self, player_level: int = 1, floor: int = 1) -> bool:
        """The quest becomes available once any player reaches floor 2."""
        return not self.completed and self.stage == 0 and floor >= 2

    def advance_stage(self) -> dict | None:
        if self.completed:
            return None
        if self.stage < len(STAGES):
            self.stage += 1
            return STAGES[self.stage - 1]
        self.complete()
        return None

    def complete(self) -> list[dict]:
        self.completed = True
        return REWARDS

    def current_objective(self) -> str:
        if self.completed:
            return "Quest complete."
        if 0 < self.stage <= len(STAGES):
            return STAGES[self.stage - 1]["objective"]
        return "Speak to " + (list(NPC_DIALOGUE) or ["the Chronicler"])[0]


def spawn_enemy(rng: random.Random | None = None) -> dict:
    """Spawn one quest enemy using its GDD stats + persisted genome."""
    rng = rng or random.Random()
    enemy = dict(rng.choice(ENEMIES))
    enemy.setdefault("genome", {})
    return enemy


def npc_line(name: str) -> str:
    return NPC_DIALOGUE.get(name, "...")
