"""Auto-generated quest assets — The Trial of Deaths in 2026

Generated by the Cardinal System Social Control module.
Source: https://en.wikipedia.org/wiki/Deaths_in_2026
Do not edit by hand; regenerate through quest_generator.py.
"""
from __future__ import annotations

import random

QUEST_TITLE = 'The Trial of Deaths in 2026'
MAP_ARCHETYPE = 'horizontal'
NARRATIVE = 'Whispers of Deaths in 2026 have reached the floating castle. An anomaly reshapes the land into a horizontal trial. Only those who unravel its origin may claim the reward.'

STAGES = [
    {
        "stage": 1,
        "description": "Investigate the rumors surrounding Deaths in 2026. \n\n\nThe following notable deaths occurred in 2026. Names are reported under the date of death, in alphabetical order. A typical entry reports information in the following sequence:Name, age, country of",
        "objective": "Speak with the Chronicler and find the anomaly site."
    },
    {
        "stage": 2,
        "description": "The anomaly's guardians emerge to test challengers.",
        "objective": "Defeat 3 Anomaly Guardians."
    },
    {
        "stage": 3,
        "description": "The heart of the horizontal reveals itself.",
        "objective": "Defeat the Avatar of Deaths in 2026 and seal the anomaly."
    }
]

NPC_DIALOGUE = {
    "The Chronicler": "Traveler... the tale of Deaths in 2026 is older than this castle. Listen well.",
    "Lost Scout": "I saw the guardians with my own eyes. Turn back, or arm yourself."
}

ENEMIES = [
    {
        "name": "Anomaly Guardian",
        "damage": 21,
        "hp": 107,
        "reward_gold": 56,
        "genome": {
            "timing_jitter": -0.1489,
            "damage_jitter": -0.1448,
            "combo_seed": 1673787892,
            "combo_shuffle_depth": 2,
            "resistance_vector": {
                "physical": 0.2158,
                "magic": 0.1325,
                "ranged": 0.0495
            },
            "entropy_at_birth": 0.7361
        }
    },
    {
        "name": "Avatar of Deaths in 2026",
        "damage": 30,
        "hp": 418,
        "reward_gold": 274,
        "genome": {
            "timing_jitter": -0.246,
            "damage_jitter": -0.1367,
            "combo_seed": 1910802443,
            "combo_shuffle_depth": 1,
            "resistance_vector": {
                "physical": 0.0044,
                "magic": 0.0454,
                "ranged": 0.3151
            },
            "entropy_at_birth": 0.7361
        }
    }
]

REWARDS = [
    {
        "item": "Relic of Deaths in 2026",
        "quantity": 1
    },
    {
        "item": "Health Potion",
        "quantity": 3
    }
]


class Quest:
    """Stage machine for 'The Trial of Deaths in 2026'."""

    def __init__(self) -> None:
        self.stage = 0
        self.completed = False

    def check_trigger(self, player_level: int = 1, floor: int = 1) -> bool:
        """The quest becomes available once any player reaches floor 2."""
        return not self.completed and self.stage == 0 and floor >= 2

    def advance_stage(self) -> dict | None:
        if self.completed:
            return None
        if self.stage < len(STAGES):
            self.stage += 1
            return STAGES[self.stage - 1]
        self.complete()
        return None

    def complete(self) -> list[dict]:
        self.completed = True
        return REWARDS

    def current_objective(self) -> str:
        if self.completed:
            return "Quest complete."
        if 0 < self.stage <= len(STAGES):
            return STAGES[self.stage - 1]["objective"]
        return "Speak to " + (list(NPC_DIALOGUE) or ["the Chronicler"])[0]


def spawn_enemy(rng: random.Random | None = None) -> dict:
    """Spawn one quest enemy using its GDD stats + persisted genome."""
    rng = rng or random.Random()
    enemy = dict(rng.choice(ENEMIES))
    enemy.setdefault("genome", {})
    return enemy


def npc_line(name: str) -> str:
    return NPC_DIALOGUE.get(name, "...")
