"""Auto-generated quest assets — The Trial of Obsession (2025 film)

Generated by the Cardinal System Social Control module.
Source: https://en.wikipedia.org/wiki/Obsession_(2025_film)
Do not edit by hand; regenerate through quest_generator.py.
"""
from __future__ import annotations

import random

QUEST_TITLE = 'The Trial of Obsession (2025 film)'
MAP_ARCHETYPE = 'horizontal'
NARRATIVE = 'Whispers of Obsession (2025 film) have reached the floating castle. An anomaly reshapes the land into a horizontal trial. Only those who unravel its origin may claim the reward.'

STAGES = [
    {
        "stage": 1,
        "description": "Investigate the rumors surrounding Obsession (2025 film). Obsession is a 2025 American supernatural psychological horror film written, directed, and edited by Curry Barker. The film follows Bear, a music store employee who buys a supernatural toy that grants",
        "objective": "Speak with the Chronicler and find the anomaly site."
    },
    {
        "stage": 2,
        "description": "The anomaly's guardians emerge to test challengers.",
        "objective": "Defeat 3 Anomaly Guardians."
    },
    {
        "stage": 3,
        "description": "The heart of the horizontal reveals itself.",
        "objective": "Defeat the Avatar of Obsession (2025 film) and seal the anomaly."
    }
]

NPC_DIALOGUE = {
    "The Chronicler": "Traveler... the tale of Obsession (2025 film) is older than this castle. Listen well.",
    "Lost Scout": "I saw the guardians with my own eyes. Turn back, or arm yourself."
}

ENEMIES = [
    {
        "name": "Anomaly Guardian",
        "damage": 16,
        "hp": 108,
        "reward_gold": 53,
        "genome": {
            "timing_jitter": 0.1973,
            "damage_jitter": 0.2374,
            "combo_seed": 299952608,
            "combo_shuffle_depth": 3,
            "resistance_vector": {
                "physical": 0.0756,
                "magic": 0.2884,
                "ranged": 0.2801
            },
            "entropy_at_birth": 1.0
        }
    },
    {
        "name": "Avatar of Obsession (2025 film)",
        "damage": 33,
        "hp": 431,
        "reward_gold": 244,
        "genome": {
            "timing_jitter": -0.1597,
            "damage_jitter": 0.2451,
            "combo_seed": 795302574,
            "combo_shuffle_depth": 1,
            "resistance_vector": {
                "physical": 0.3108,
                "magic": 0.2726,
                "ranged": 0.2412
            },
            "entropy_at_birth": 1.0
        }
    }
]

REWARDS = [
    {
        "item": "Relic of Obsession (2025 film)",
        "quantity": 1
    },
    {
        "item": "Health Potion",
        "quantity": 3
    }
]


class Quest:
    """Stage machine for 'The Trial of Obsession (2025 film)'."""

    def __init__(self) -> None:
        self.stage = 0
        self.completed = False

    def check_trigger(self, player_level: int = 1, floor: int = 1) -> bool:
        """The quest becomes available once any player reaches floor 2."""
        return not self.completed and self.stage == 0 and floor >= 2

    def advance_stage(self) -> dict | None:
        if self.completed:
            return None
        if self.stage < len(STAGES):
            self.stage += 1
            return STAGES[self.stage - 1]
        self.complete()
        return None

    def complete(self) -> list[dict]:
        self.completed = True
        return REWARDS

    def current_objective(self) -> str:
        if self.completed:
            return "Quest complete."
        if 0 < self.stage <= len(STAGES):
            return STAGES[self.stage - 1]["objective"]
        return "Speak to " + (list(NPC_DIALOGUE) or ["the Chronicler"])[0]


def spawn_enemy(rng: random.Random | None = None) -> dict:
    """Spawn one quest enemy using its GDD stats + persisted genome."""
    rng = rng or random.Random()
    enemy = dict(rng.choice(ENEMIES))
    enemy.setdefault("genome", {})
    return enemy


def npc_line(name: str) -> str:
    return NPC_DIALOGUE.get(name, "...")
