"""Auto-generated quest assets — The Trial of Bharathiraja

Generated by the Cardinal System Social Control module.
Source: https://en.wikipedia.org/wiki/Bharathiraja
Do not edit by hand; regenerate through quest_generator.py.
"""
from __future__ import annotations

import random

QUEST_TITLE = 'The Trial of Bharathiraja'
MAP_ARCHETYPE = 'vertical'
NARRATIVE = 'Whispers of Bharathiraja have reached the floating castle. An anomaly reshapes the land into a vertical trial. Only those who unravel its origin may claim the reward.'

STAGES = [
    {
        "stage": 1,
        "description": "Investigate the rumors surrounding Bharathiraja. Bharathiraja was an Indian film director, producer, screenwriter and actor who worked mainly in the Tamil film industry. Making his debut in 1977 with 16 Vayathinile, he was known for realistic and se",
        "objective": "Speak with the Chronicler and find the anomaly site."
    },
    {
        "stage": 2,
        "description": "The anomaly's guardians emerge to test challengers.",
        "objective": "Defeat 3 Anomaly Guardians."
    },
    {
        "stage": 3,
        "description": "The heart of the vertical reveals itself.",
        "objective": "Defeat the Avatar of Bharathiraja and seal the anomaly."
    }
]

NPC_DIALOGUE = {
    "The Chronicler": "Traveler... the tale of Bharathiraja is older than this castle. Listen well.",
    "Lost Scout": "I saw the guardians with my own eyes. Turn back, or arm yourself."
}

ENEMIES = [
    {
        "name": "Anomaly Guardian",
        "damage": 16,
        "hp": 123,
        "reward_gold": 71,
        "genome": {
            "timing_jitter": 0.2184,
            "damage_jitter": -0.0593,
            "combo_seed": 732160985,
            "combo_shuffle_depth": 1,
            "resistance_vector": {
                "physical": 0.1538,
                "magic": 0.0947,
                "ranged": 0.218
            },
            "entropy_at_birth": 0.9774
        }
    },
    {
        "name": "Avatar of Bharathiraja",
        "damage": 31,
        "hp": 352,
        "reward_gold": 275,
        "genome": {
            "timing_jitter": -0.3576,
            "damage_jitter": 0.1504,
            "combo_seed": 1678977841,
            "combo_shuffle_depth": 3,
            "resistance_vector": {
                "physical": 0.3382,
                "magic": 0.3527,
                "ranged": 0.2989
            },
            "entropy_at_birth": 0.9774
        }
    }
]

REWARDS = [
    {
        "item": "Relic of Bharathiraja",
        "quantity": 1
    },
    {
        "item": "Health Potion",
        "quantity": 3
    }
]


class Quest:
    """Stage machine for 'The Trial of Bharathiraja'."""

    def __init__(self) -> None:
        self.stage = 0
        self.completed = False

    def check_trigger(self, player_level: int = 1, floor: int = 1) -> bool:
        """The quest becomes available once any player reaches floor 2."""
        return not self.completed and self.stage == 0 and floor >= 2

    def advance_stage(self) -> dict | None:
        if self.completed:
            return None
        if self.stage < len(STAGES):
            self.stage += 1
            return STAGES[self.stage - 1]
        self.complete()
        return None

    def complete(self) -> list[dict]:
        self.completed = True
        return REWARDS

    def current_objective(self) -> str:
        if self.completed:
            return "Quest complete."
        if 0 < self.stage <= len(STAGES):
            return STAGES[self.stage - 1]["objective"]
        return "Speak to " + (list(NPC_DIALOGUE) or ["the Chronicler"])[0]


def spawn_enemy(rng: random.Random | None = None) -> dict:
    """Spawn one quest enemy using its GDD stats + persisted genome."""
    rng = rng or random.Random()
    enemy = dict(rng.choice(ENEMIES))
    enemy.setdefault("genome", {})
    return enemy


def npc_line(name: str) -> str:
    return NPC_DIALOGUE.get(name, "...")
