"""Auto-generated quest assets — The Trial of 2026 Peruvian general election

Generated by the Cardinal System Social Control module.
Source: https://en.wikipedia.org/wiki/2026_Peruvian_general_election
Do not edit by hand; regenerate through quest_generator.py.
"""
from __future__ import annotations

import random

QUEST_TITLE = 'The Trial of 2026 Peruvian general election'
MAP_ARCHETYPE = 'horizontal'
NARRATIVE = 'Whispers of 2026 Peruvian general election have reached the floating castle. An anomaly reshapes the land into a horizontal trial. Only those who unravel its origin may claim the reward.'

STAGES = [
    {
        "stage": 1,
        "description": "Investigate the rumors surrounding 2026 Peruvian general election. General elections were held in Peru from 12 to 13 April 2026 to elect the president, vice presidents, and the Congress of the Republic of Peru. As no presidential candidate achieved a majority of vote",
        "objective": "Speak with the Chronicler and find the anomaly site."
    },
    {
        "stage": 2,
        "description": "The anomaly's guardians emerge to test challengers.",
        "objective": "Defeat 3 Anomaly Guardians."
    },
    {
        "stage": 3,
        "description": "The heart of the horizontal reveals itself.",
        "objective": "Defeat the Avatar of 2026 Peruvian general election and seal the anomaly."
    }
]

NPC_DIALOGUE = {
    "The Chronicler": "Traveler... the tale of 2026 Peruvian general election is older than this castle. Listen well.",
    "Lost Scout": "I saw the guardians with my own eyes. Turn back, or arm yourself."
}

ENEMIES = [
    {
        "name": "Anomaly Guardian",
        "damage": 17,
        "hp": 104,
        "reward_gold": 64,
        "genome": {
            "timing_jitter": 0.01,
            "damage_jitter": 0.1806,
            "combo_seed": 1692189565,
            "combo_shuffle_depth": 1,
            "resistance_vector": {
                "physical": 0.0016,
                "magic": 0.2062,
                "ranged": 0.243
            },
            "entropy_at_birth": 0.7361
        }
    },
    {
        "name": "Avatar of 2026 Peruvian general election",
        "damage": 37,
        "hp": 407,
        "reward_gold": 230,
        "genome": {
            "timing_jitter": -0.0741,
            "damage_jitter": -0.0038,
            "combo_seed": 1029305582,
            "combo_shuffle_depth": 2,
            "resistance_vector": {
                "physical": 0.0829,
                "magic": 0.2507,
                "ranged": 0.3199
            },
            "entropy_at_birth": 0.7361
        }
    }
]

REWARDS = [
    {
        "item": "Relic of 2026 Peruvian general election",
        "quantity": 1
    },
    {
        "item": "Health Potion",
        "quantity": 3
    }
]


class Quest:
    """Stage machine for 'The Trial of 2026 Peruvian general election'."""

    def __init__(self) -> None:
        self.stage = 0
        self.completed = False

    def check_trigger(self, player_level: int = 1, floor: int = 1) -> bool:
        """The quest becomes available once any player reaches floor 2."""
        return not self.completed and self.stage == 0 and floor >= 2

    def advance_stage(self) -> dict | None:
        if self.completed:
            return None
        if self.stage < len(STAGES):
            self.stage += 1
            return STAGES[self.stage - 1]
        self.complete()
        return None

    def complete(self) -> list[dict]:
        self.completed = True
        return REWARDS

    def current_objective(self) -> str:
        if self.completed:
            return "Quest complete."
        if 0 < self.stage <= len(STAGES):
            return STAGES[self.stage - 1]["objective"]
        return "Speak to " + (list(NPC_DIALOGUE) or ["the Chronicler"])[0]


def spawn_enemy(rng: random.Random | None = None) -> dict:
    """Spawn one quest enemy using its GDD stats + persisted genome."""
    rng = rng or random.Random()
    enemy = dict(rng.choice(ENEMIES))
    enemy.setdefault("genome", {})
    return enemy


def npc_line(name: str) -> str:
    return NPC_DIALOGUE.get(name, "...")
