"""Auto-generated quest assets — The Trial of 2026 FIFA World Cup

Generated by the Cardinal System Social Control module.
Source: https://en.wikipedia.org/wiki/2026_FIFA_World_Cup
Do not edit by hand; regenerate through quest_generator.py.
"""
from __future__ import annotations

import random

QUEST_TITLE = 'The Trial of 2026 FIFA World Cup'
MAP_ARCHETYPE = 'horizontal'
NARRATIVE = 'Whispers of 2026 FIFA World Cup have reached the floating castle. An anomaly reshapes the land into a horizontal trial. Only those who unravel its origin may claim the reward.'

STAGES = [
    {
        "stage": 1,
        "description": "Investigate the rumors surrounding 2026 FIFA World Cup. The 2026 FIFA World Cup is the current and 23rd edition of the FIFA World Cup, the quadrennial international men's soccer championship contested by the national teams of the member associations of FIF",
        "objective": "Speak with the Chronicler and find the anomaly site."
    },
    {
        "stage": 2,
        "description": "The anomaly's guardians emerge to test challengers.",
        "objective": "Defeat 3 Anomaly Guardians."
    },
    {
        "stage": 3,
        "description": "The heart of the horizontal reveals itself.",
        "objective": "Defeat the Avatar of 2026 FIFA World Cup and seal the anomaly."
    }
]

NPC_DIALOGUE = {
    "The Chronicler": "Traveler... the tale of 2026 FIFA World Cup is older than this castle. Listen well.",
    "Lost Scout": "I saw the guardians with my own eyes. Turn back, or arm yourself."
}

ENEMIES = [
    {
        "name": "Anomaly Guardian",
        "damage": 16,
        "hp": 142,
        "reward_gold": 53,
        "genome": {
            "timing_jitter": 0.0596,
            "damage_jitter": 0.3521,
            "combo_seed": 993048237,
            "combo_shuffle_depth": 2,
            "resistance_vector": {
                "physical": 0.3297,
                "magic": 0.0747,
                "ranged": 0.3605
            },
            "entropy_at_birth": 1.0
        }
    },
    {
        "name": "Avatar of 2026 FIFA World Cup",
        "damage": 32,
        "hp": 346,
        "reward_gold": 273,
        "genome": {
            "timing_jitter": 0.1435,
            "damage_jitter": 0.169,
            "combo_seed": 795783018,
            "combo_shuffle_depth": 1,
            "resistance_vector": {
                "physical": 0.0798,
                "magic": 0.14,
                "ranged": 0.0658
            },
            "entropy_at_birth": 1.0
        }
    }
]

REWARDS = [
    {
        "item": "Relic of 2026 FIFA World Cup",
        "quantity": 1
    },
    {
        "item": "Health Potion",
        "quantity": 3
    }
]


class Quest:
    """Stage machine for 'The Trial of 2026 FIFA World Cup'."""

    def __init__(self) -> None:
        self.stage = 0
        self.completed = False

    def check_trigger(self, player_level: int = 1, floor: int = 1) -> bool:
        """The quest becomes available once any player reaches floor 2."""
        return not self.completed and self.stage == 0 and floor >= 2

    def advance_stage(self) -> dict | None:
        if self.completed:
            return None
        if self.stage < len(STAGES):
            self.stage += 1
            return STAGES[self.stage - 1]
        self.complete()
        return None

    def complete(self) -> list[dict]:
        self.completed = True
        return REWARDS

    def current_objective(self) -> str:
        if self.completed:
            return "Quest complete."
        if 0 < self.stage <= len(STAGES):
            return STAGES[self.stage - 1]["objective"]
        return "Speak to " + (list(NPC_DIALOGUE) or ["the Chronicler"])[0]


def spawn_enemy(rng: random.Random | None = None) -> dict:
    """Spawn one quest enemy using its GDD stats + persisted genome."""
    rng = rng or random.Random()
    enemy = dict(rng.choice(ENEMIES))
    enemy.setdefault("genome", {})
    return enemy


def npc_line(name: str) -> str:
    return NPC_DIALOGUE.get(name, "...")
